### ISSUE TITLE
Is it possible to upload a text file in the front-end?

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-tab-generator#22]
Is there an annotation to upload a text file as in the INTEGRAL frontend?

**Comment by dsavchenko** [comment]
Not yet. There is an issue opened https://github.com/oda-hub/dispatcher-plugin-nb2workflow/issues/50 to add this feature. It will also require changes to main dispatcher code (I suppose there is also an issue opened, can't find it now) as well as frontend/oda_api to actually use it. 

Meanwhile the workaround is to upload the file somewhere and give its url as a String input parameter. 
This approach will then be supported as FileURL input type in a backward-compatible way.

**Comment by ferrigno** [comment]
Ok, thanks, I can change it to a string fro now. In oda_api, we can pass the file content as a string (parameter catalog)

**Comment by dsavchenko** [comment]
The catalog parameter is very integral-specific and is processed in a very special way by dispatcher. In the request to backend it gets transformed to some json, produced from the preprocessed catalogue file.

**Comment by ferrigno** [comment]
Ok, thanks, I can change it to a string fro now. In oda_api, we can pass the file content as a string (parameter catalog)
