### ISSUE TITLE
Establish an order for parameters in frontend

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-tab-generator#25]
In the front end, it is important to establish an order for parameters so to group them for functionality. 
It does not seem to be implemented, according to a previous conversation.

**Comment by dsavchenko** [comment]
The order of the parameters is preserved as in notebook now via https://github.com/oda-hub/nb2workflow/pull/165

**Comment by ferrigno** [comment]
We should mention it in the doc

Il Ven 23 Ago 2024, 12:03 Denys Savchenko ***@***.***> ha
scritto:
