### ISSUE TITLE
INTEGRAL longterm Tab still in the frontend after removing "live-workflow" tag

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-tab-generator#27]
During development, I realize that it would have been better to have two different tabs: one for ISGRI and one for JEM-X.
For the moment, I cannot delete the repository
https://gitlab.renkulab.io/astronomy/mmoda/ibis-isgri-spectrum
= INTEGRAL longterm
but it should not be anymore a valid tab.

**Comment by dsavchenko** [comment]
There is currently no mechanism implemented to automatically remove tabs. 
I deactivated it manually.

**Comment by ferrigno** [comment]
Sorry about this additional task, I was not aware.
