### ISSUE TITLE
Which annotations are valid for Tab generation ? (X-rays for JEM-X)

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-tab-generator#32]
I tried to use MMODA X-rays for JEM-X 
![image](https://github.com/oda-hub/frontend-tab-generator/assets/2527219/76fad10d-0039-48c6-b48b-488adf2ba672)
but it does not appear in the FrontEnd
![image](https://github.com/oda-hub/frontend-tab-generator/assets/2527219/bc3ad983-6adc-4b76-8ce6-d279218aeda8)
How can I do it?

**Comment by volodymyrss** [comment]
As lightly indicated in the [manual](https://odahub.io/docs/guide-development/), "MM Gamma-rays" becomes "Gamma-rays" and anything . I just added an extra sentence there which should make sufficiently clear that there is no restriction on what comes after "MM ". 
Please reopen the issue if unclear!
