### ISSUE TITLE
could we put somewhere at the end the instrument version?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-tab-generator#35]

**Comment by dsavchenko** [comment]
It's possible. Where do you propose to put it? I'm not sure if it will look nice in the instrument tab ("versions" now are just commit ids). 
@andriineronov what do you think?
@motame @burnout87 maybe you may propose (not every place in the frontend is equally easily accessible for tab generator, I suppose)

**Comment by burnout87** [comment]
What about right below the name?

![image](https://github.com/oda-hub/frontend-tab-generator/assets/3757833/87cde8f3-b9cf-48a8-97a2-423814bb0033)

It can easily be added from the `.install` file and then in the main template file of the module

**Comment by volodymyrss** [comment]
> I think this can be useful... May be on the instrument-specific parameter panel, e.g. at the bottom?

That's what I thought too. A version as in time, commit/tag (git describe --always --tags) linking to the original repo at this revision.

**Comment by burnout87** [comment]
something like that ?

![image](https://github.com/oda-hub/frontend-tab-generator/assets/3757833/3cdc4237-5815-4f41-9ef5-eedd4ad45562)


![image](https://github.com/oda-hub/frontend-tab-generator/assets/3757833/d33a6d5f-1d94-4146-8ce4-5302198f627a)

**Comment by volodymyrss** [comment]
I'd say yes, like that, but with the version of the instrument. 

What you put now is some other version of the frontend/dispatcher, and by the way not such a bad idea to put them somewhere too. Somewhere at the bottom?

**Comment by volodymyrss** [comment]
> > I'd say yes, like that, but with the version of the instrument.
> Which version are you referring to ?

Version of the instrument repository. Maybe it's better that @dsavchenko just adds it so you can see. 
 
> > What you put now is some other version of the frontend/dispatcher, and by the way not such a bad idea to put them somewhere too. Somewhere at the bottom?
> what I have put now is the output of the command `git describe --tags`, from the repo of the integral plugin (since I am testing for the ISGRI instrument).

For ISGRI instrument this would be the way. But it's not so critical to put version for this one since it's not updating often.

**Comment by volodymyrss** [comment]
> > For ISGRI instrument this would be the way. But it's not so critical to put version for this one since it's not updating often.
> 
> As for the position, is it ok?

I suppose so.
