### ISSUE TITLE
How to use ontology to create front-end tab ? 

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-tab-generator#42]
An example:
the class https://odahub.io/ontology/#FileReference and its derived
file u r l  
p o s i x path 

In https://renkulab.io/projects/astronomy/mmoda/jemx-expert/files/blob/mosaic.ipynb
I specified a default for file_url, 

but the frontend displays an upload widget and the default value is not preserved when I switch with the radial button

![image](https://github.com/oda-hub/ontology/assets/2527219/39f0fe9c-11de-498a-80da-88695c72dfc0)

**Comment by burnout87** [comment]
the default_value was not set for the url type

**Comment by burnout87** [comment]
with fix in #41 :

simply the default_value was not set

![image](https://github.com/oda-hub/frontend-tab-generator/assets/3757833/23f96aaa-d8d4-46d8-92f4-45fd8345ffe3)

**Comment by dsavchenko** [comment]
As far as I remember (@burnout87 correct if I'm wrong) we decided that on the backend-dispatcher interaction both FileURL and POSIXPath works the same, so the implementation doesn't differ. 
We may anyway explore if it's easily possible to preserve the default value if it's FileURL. Then we need to change the issue tiutle to track it

**Comment by volodymyrss** [comment]
I am not totally sure what you mean @ferrigno , I think the issue text is not really written in complete sentences, and to title is way too generic to make sense. 

Could you please clarify what you are asking apart from what @burnout87 just changed and extra [manual](https://github.com/oda-hub/hugo-odahub/issues/104) that's needed?
