### ISSUE TITLE
Default URL not shown for oda:FileURL type and parameter not used

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-tab-generator#45]
In https://gitlab.renkulab.io/astronomy/mmoda/jemx-expert/-/blob/main/mosaic.ipynb?ref_type=heads
the parameter 
isdc_cat_url
is an URL, but in the generated tab defaults to "Upload a File"

Moreover, the following message appears

"
Please note that argument isdc_cat_url_type is not used
"

**Comment by burnout87** [comment]
> In https://gitlab.renkulab.io/astronomy/mmoda/jemx-expert/-/blob/main/mosaic.ipynb?ref_type=heads the parameter isdc_cat_url is an URL, but in the generated tab defaults to "Upload a File"

that's weird, I'll try to build it locally
> 
> Moreover, the following message appears
> 
> " Please note that argument isdc_cat_url_type is not used "

That is expected, that argument simply tells whether the url or the fille have been passed to the form submitted to the dispatcher, but that argument, is actually never used (and yes, it should be discarded)

**Comment by burnout87** [comment]
I managed to build it locally, and I guess, this is how you'd expect to see it:

![image](https://github.com/user-attachments/assets/193d5032-a35c-4ead-95f8-ba4d7965093e)

**Comment by ferrigno** [comment]
Good that at least locally it worked as expected. The service ended with an error that was corrected in some following commits. This means that the build was not up to date. Since then, I received two messages with a build that worked. I will try again next week..

**Comment by burnout87** [comment]
Did it work @ferrigno  ?

**Comment by ferrigno** [comment]
Yes, I close it.
