### ISSUE TITLE
oda:label annotation not working

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-tab-generator#46]
I tried to put label annotations in my notebooks, see e.g.

https://gitlab.renkulab.io/astronomy/mmoda/jemx-expert/-/blob/main/mosaic.ipynb?ref_type=heads

but it is not used (at least in the Geneva instance)

**Comment by dsavchenko** [comment]
I think it's still in development
@burnout87  please confirm

**Comment by burnout87** [comment]
exactly, will come with #40

**Comment by burnout87** [comment]
an example on how it will look like:

![image](https://github.com/user-attachments/assets/44d096cd-4291-4920-8b0b-1818083d53f6)

with the following notebook (note the parameter `file_URL`) 

https://gitlab.renkulab.io/gabriele.barni/photoz-euclid/-/blob/master/Run_Phosphoros_preComputedMG.ipynb
