### ISSUE TITLE
frontend crashes with new crbeam

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-tab-generator#53]
```
[Sign in ](https://localhost:8443/mmoda/user/login)Sign up
[×](https://localhost:8443/#)
Error message
ParseError: syntax error, unexpected '",' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in module_load_include() (line 1037 of /var/www/mmoda/sites/all/modules/mmoda/instruments/mmoda_crbeam/mmoda_crbeam.inc).
```

**Comment by volodymyrss** [comment]
No, as the title says, the frontend crashes. I manually removed crbeam module from the frontend which left the error message.

You sure use the latest crbeam version, from yesterday? You can see it broke in CI too.

**Comment by volodymyrss** [comment]
@okolo , I will try to revert your last change of yesterday https://gitlab.renkulab.io/astronomy/mmoda/crbeam/-/commit/9ecc62447d59896e96984e84da2403a8d2cebd21

**Comment by burnout87** [comment]
> 
> You sure use the latest crbeam version, from yesterday? You can see it broke in CI too.

This one right: a850e30fc46d95e5b896473020c6b257385909b7 

I tried it and I could build it (using the master version of the tab-generator)

**Comment by volodymyrss** [comment]
hm, could you please attach here `crbeam.inc` you are getting? For me it causes this issue.

**Comment by burnout87** [comment]
> You can upload the file if you gzip it. Here [crbeam.inc.gz](https://github.com/user-attachments/files/17013663/crbeam.inc.gz)

Ok thanks. I see the error that causes the crash

**Comment by burnout87** [comment]
And I can confirm that with the latest PR #49 , it will be fixed

**Comment by volodymyrss** [comment]
Could you check that the problem is present with the latest integrated image? ` odahub/oda-bot:edff3c9-240916025940-master` built in https://github.com/oda-hub/oda-bot/actions/runs/10876814663/job/30177268543 . 

If yes we should merge the fix ASAP.

**Comment by burnout87** [comment]
Yes, I see from the log that the bot cloned 2ee02755ff8b1451dfed406292f69e014b6c5458 , which has the bug

**Comment by volodymyrss** [comment]
We should merge today. Either the whole Euclid thing or just the bug fix.

**Comment by volodymyrss** [comment]
The deployed version still failed. Maybe some rushed deployement. Could you cross check that the latest bot image is producing good frontend tab?

**Comment by burnout87** [comment]
the latest bot image is checking 3f5bd3f4d1dfe0eba357cb548e090b4e9ffb5012 commit of the generator, so correctly

locally, I could also generate it properly

but at the moment, on the frontend I dont see an error about the `*.inc` file, perhaps it's something related to the installation of the module itself?

Can you share the new  mmoda_crbeam.inc file ? thanks

**Comment by volodymyrss** [comment]
I can not easily do it right now. Could you run the generator in this image and see what you get?

It does not show error because I deleted the instrument directory again.

**Comment by volodymyrss** [comment]
still getting this

```
ParseError: syntax error, unexpected '",' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in module_load_include() (line 1037 of /var/www/mmoda/sites/all/modules/mmoda/instruments/mmoda_crbeam/mmoda_crbeam.inc).
```

**Comment by volodymyrss** [comment]
[mmoda_crbeam.inc.gz](https://github.com/user-attachments/files/17016717/mmoda_crbeam.inc.gz)

**Comment by burnout87** [comment]
that's really weird, the error is exactly the same, despite having seen the bot checking out the latest commit of the generator

**Comment by volodymyrss** [comment]
could you check what's in the container? do `docker run -it ...` and look inside it for the code you changed for the bugfix.

**Comment by burnout87** [comment]
I did some investigation and it is running the latest code of the generator
